name: lameness_detection_env
channels:
  - pytorch
  - defaults
dependencies:
  - matplotlib=3.3.*
  - numpy=1.19.*
  - opencv=3.3.*
  - pandas=1.1.*
  - python>=3.6
  - pytorch=1.7.0
  - scikit-learn=0.23.0
  - torchvision=0.8.1
